### ISSUE TITLE
Installer hangs and doesn't complete

### ISSUE THREAD

**Issue by hhff** [nadavshatz/ember-cli-foundation-sass#27]
Hi there!

I love this lib - I use it for just about everything I do.  However, lately it's been hanging on install.  I've heard this from another dev - and recently hit it myself.

Steps to repro:
```
ember new app
cd app
ember install ember-cli-foundation-sass
```

It gets to here and just hangs:

![screen shot 2015-05-10 at 11 18 46 am](https://cloud.githubusercontent.com/assets/2865404/7554865/f1d3e390-f706-11e4-839e-9c2f65086555.png)

```
ember -v

version: 0.2.3
node: 0.10.37
npm: 2.7.6
```

Anyone else seen this?  @ninjz had this issue also.

**Comment by nadavshatz** [comment]
Sorry for never responding, the repo has changed hands.
I'm closing all old issues as they are very old.

Please open a new issue if you are experiencing issues with the new version.
