### ISSUE TITLE
JS not working 

### ISSUE THREAD

**Issue by aalasolutions** [nadavshatz/ember-cli-foundation-sass#29]
Hi

I have included / followed your tutorial, CSS is working fine. 

    import Ember from 'ember';
    
    export default Ember.Component.extend({
      didInitAttrs() {
        Ember.run.schedule("afterRender", function () {
          Ember.$(document).foundation();
          console.error('test');
        });
      }
    }) ;

When page is loaded it is giving me following error

`Uncaught TypeError: Ember.default.$(...).foundation is not a function`

**Comment by sly7-7** [comment]
I think you should `import $ from 'jquery'` and use $.foundation() directly

**Comment by nadavshatz** [comment]
Sorry for never responding, the repo has changed hands.
I'm closing all old issues as they are very old.

Please open a new issue if you are experiencing issues with the new version.
