### ISSUE TITLE
Modernizr not found after version 3.0.0

### ISSUE THREAD

**Issue by wzrdtales** [nadavshatz/ember-cli-foundation-sass#31]
Since the foundation dependency of modernizr resolves to version 3.0.0, there seems there have been introduced some incompatibilities.

The following error gets thrown
    
    ENOENT, no such file or directory '/tmp/concat_with_maps-input_base_path-c6LK6QBl.tmp/0/bower_components/modernizr/modernizr.js'

**Comment by scolyer** [comment]
I'm having the same issue.

**Comment by sharpshark28** [comment]
Same here. Would love to know a fix :+1:

**Comment by bpang** [comment]
Thanks!

**Comment by scolyer** [comment]
Thanks @sharpshark28 :)

**Comment by nadavshatz** [comment]
Sorry for never responding, the repo has changed hands.
I'm closing all old issues as they are very old.

Please open a new issue if you are experiencing issues with the new version.
