### ISSUE TITLE
Deprecation warning: sassOptions should be moved to your Brocfile

### ISSUE THREAD

**Issue by davidgoli** [nadavshatz/ember-cli-foundation-sass#32]
When starting an Ember server with ember-cli-foundation-sass installed, this warning is emitted.

**Comment by givanse** [comment]
most likely an issue with ember-cli-sass and not this project per se

**Comment by davidgoli** [comment]
It's fixed in ember-cli-sass 5.3.0, this project just needs a version bump for that.

**Comment by nadavshatz** [comment]
This can be closed once the version is bumped.

**Comment by nadavshatz** [comment]
Resolved with Version 2.0
