### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by nadavshatz** [nadavshatz/ember-cli-foundation-sass#36]
A PR was merged to solve #32 but no new version was released.

Please bump the version and release it.

Thanks!

**Comment by johnnybridges** [comment]
@nadavshatz sorry, we aren't able to maintain this repo any longer. Rather than removing it, would you like to take over?

**Comment by nadavshatz** [comment]
Sure I can take over it and into my org.
We can spend a bit more time updating everything and releasing a new version at the very least.

**Comment by johnnybridges** [comment]
@nadavshatz Ok great, i'll transfer it over to you now. Which handle shall I transfer to?

**Comment by nadavshatz** [comment]
Just do to me @nadavshatz And I can transfer it to the org later.

thanks! will it just work for NPM pushing ?

**Comment by johnnybridges** [comment]
Good question, @Globegitter will need to answer that unfortunately. He set up this repo whilst working for us, but has since left and we no longer use it. Hence it's in this current state!

**Comment by nadavshatz** [comment]
Got you, I guess the main purpose is to actually push new versions into NPM which would make the whole thing a little pointless otherwise :)

**Comment by Globegitter** [comment]
@nadavshatz I should be able to give you push access to NPM. Will have a look today.

**Comment by johnnybridges** [comment]
@Globegitter thank you

**Comment by nadavshatz** [comment]
@Globegitter any updates?

**Comment by Globegitter** [comment]
Sorry for the delay, you should have access now @nadavshatz :)

**Comment by nadavshatz** [comment]
@Globegitter Thank you!
