### ISSUE TITLE
Error: Using `app.import` with a file in the root of `vendor`...

### ISSUE THREAD

**Issue by matthewrobb** [nadavshatz/ember-cli-foundation-sass#9]
I am getting this error today:

```
Using `app.import` with a file in the root of `vendor/` causes a significant performance penalty. Please move `bower_components\foundation\js\foundation.js` into a subdirectory.
```

**Comment by nadavshatz** [comment]
Sorry for never responding, the repo has changed hands.
I'm closing all old issues as they are very old.

Please open a new issue if you are experiencing issues with the new version.
